export interface StoreTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: string;
  tags: string[];
  fields: any[];
  defaultTip?: string;
  defaultDurum?: string;
  statusFlow?: string[];
  numbering?: any;
}

export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'Tümü', icon: '🗂️' },
  { id: 'imar', label: 'İmar & Planlama', icon: '📐' },
  { id: 'ruhsat', label: 'Ruhsat', icon: '🏗️' },
  { id: 'yazisma', label: 'Yazışma', icon: '✉️' },
  { id: 'hukuk', label: 'Hukuk & Tebligat', icon: '⚖️' },
  { id: 'muhasebe', label: 'Muhasebe', icon: '🧾' },
  { id: 'is_sagligi', label: 'İş Sağlığı', icon: '🦺' },
  { id: 'genel', label: 'Genel', icon: '📄' },
];

export const BUILTIN_TEMPLATES: StoreTemplate[] = [
  {
    id: 'imar_18_madde',
    name: '18. Madde İmar Uygulaması',
    description: 'İmar Kanunu 18. madde parselasyon ve düzenleme dosya takip şablonu',
    icon: '📐',
    color: '#10b981',
    category: 'imar',
    tags: ['imar', 'parselasyon', 'encümen', 'tescil'],
    defaultTip: 'ic',
    defaultDurum: 'hazırlık',
    statusFlow: ['hazırlık', 'encumende', 'askida', 'itirazli', 'tescil', 'tamamlandi'],
    fields: [
      { key: 'dosya_no', label: 'Dosya No', type: 'text', required: true, width: 'sm', hint: 'Örn: 2026/18-01' },
      { key: 'ada_parsel', label: 'Ada / Parsel', type: 'text', required: false, width: 'sm', hint: 'Örn: 200/50' },
      { key: 'ds_no', label: 'DS No', type: 'text', required: false, width: 'sm', hint: 'Düzenleme Sahası No' },
      { key: 'basvuru_sahibi', label: 'Başvuru Sahibi', type: 'text', required: true, width: 'lg' },
      { key: 'ilce', label: 'İlçe', type: 'text', required: true, width: 'md' },
      { key: 'mahalle', label: 'Mahalle', type: 'text', required: true, width: 'md' },
      { key: 'ada_no', label: 'Ada No', type: 'text', required: false, width: 'sm' },
      { key: 'parsel_no', label: 'Parsel No', type: 'text', required: false, width: 'sm' },
      { key: 'alan', label: 'Alan (m²)', type: 'text', required: false, width: 'sm' },
      { key: 'encumen_no', label: 'Encümen Karar No', type: 'text', required: false, width: 'md' },
      { key: 'askiya_cikis_tarihi', label: 'Askıya Çıkış Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'itiraz_sayisi', label: 'İtiraz Sayısı', type: 'text', required: false, width: 'sm' },
      { key: 'tescil_durumu', label: 'Tescil Durumu', type: 'select', required: false, width: 'md', options: ['Hazırlık', 'Encümende', 'Askıda', 'İtirazlı', 'Tescile Gönderildi', 'Tescil Edildi'] },
      { key: 'aciklama', label: 'Açıklama', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'insaat_ruhsat',
    name: 'İnşaat Ruhsatı Takibi',
    description: 'Yapı ruhsatı başvuru ve onay süreçlerini takip etmek için şablon',
    icon: '🏗️',
    color: '#f59e0b',
    category: 'ruhsat',
    tags: ['ruhsat', 'inşaat', 'yapı', 'onay'],
    defaultTip: 'gelen',
    defaultDurum: 'beklemede',
    numbering: { pattern: '{YIL}-R-{YIL_SIRA_NO:04d}', autoIncrement: true, resetPerYear: true, yearField: 'yil', seqField: 'yil_sira_no' },
    fields: [
      { key: 'ruhsat_no', label: 'Ruhsat No', type: 'text', required: true, width: 'sm' },
      { key: 'basvuru_sahibi', label: 'Başvuru Sahibi', type: 'text', required: true, width: 'lg' },
      { key: 'tc_no', label: 'TC Kimlik No', type: 'text', required: false, width: 'md' },
      { key: 'ilce', label: 'İlçe', type: 'text', required: true, width: 'md' },
      { key: 'mahalle', label: 'Mahalle', type: 'text', required: true, width: 'md' },
      { key: 'ada_no', label: 'Ada No', type: 'text', required: false, width: 'sm' },
      { key: 'parsel_no', label: 'Parsel No', type: 'text', required: false, width: 'sm' },
      { key: 'yapi_sinifi', label: 'Yapı Sınıfı', type: 'select', required: false, width: 'sm', options: ['I. Sınıf', 'II. Sınıf', 'III. Sınıf', 'IV. Sınıf', 'V. Sınıf'] },
      { key: 'insaat_alani', label: 'İnşaat Alanı (m²)', type: 'text', required: false, width: 'sm' },
      { key: 'kat_adedi', label: 'Kat Adedi', type: 'text', required: false, width: 'sm' },
      { key: 'mimar', label: 'Proje Mimarı', type: 'text', required: false, width: 'md' },
      { key: 'basvuru_tarihi', label: 'Başvuru Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'onay_tarihi', label: 'Onay Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'ruhsat_durumu', label: 'Ruhsat Durumu', type: 'select', required: false, width: 'md', options: ['Başvuru', 'İncelemede', 'Eksik Belge', 'Onaylandı', 'Reddedildi', 'İptal'] },
      { key: 'aciklama', label: 'Açıklama', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'yazi_takip',
    name: 'Yazı / Dilekçe Takibi',
    description: 'Kurumlar arası yazışma ve dilekçe takip şablonu',
    icon: '✉️',
    color: '#6366f1',
    category: 'yazisma',
    tags: ['yazı', 'dilekçe', 'yazışma', 'evrak'],
    defaultTip: 'gelen',
    defaultDurum: 'beklemede',
    numbering: { pattern: '{YIL}/{YIL_SIRA_NO:05d}', autoIncrement: true, resetPerYear: true, yearField: 'yil', seqField: 'yil_sira_no' },
    fields: [
      { key: 'evrak_no', label: 'Evrak No', type: 'text', required: true, width: 'sm' },
      { key: 'konu', label: 'Konu', type: 'text', required: true, width: 'full' },
      { key: 'gonderen', label: 'Gönderen', type: 'text', required: true, width: 'lg' },
      { key: 'alici', label: 'Alıcı', type: 'text', required: false, width: 'lg' },
      { key: 'havale_makam', label: 'Havale Makamı', type: 'text', required: false, width: 'md' },
      { key: 'havale_tarihi', label: 'Havale Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'cevap_suresi', label: 'Cevap Süresi (gün)', type: 'text', required: false, width: 'sm' },
      { key: 'oncelik', label: 'Öncelik', type: 'select', required: false, width: 'sm', options: ['Normal', 'Acele', 'Çok Acele', 'Günlü'] },
      { key: 'gizlilik', label: 'Gizlilik', type: 'select', required: false, width: 'sm', options: ['Açık', 'Hizmete Özel', 'Gizli', 'Çok Gizli'] },
      { key: 'cevap_durumu', label: 'Cevap Durumu', type: 'select', required: false, width: 'md', options: ['Bekliyor', 'Cevaplandı', 'Arşivlendi', 'İptal'] },
      { key: 'aciklama', label: 'Açıklama / Not', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'tebligat_takip',
    name: 'Tebligat Takibi',
    description: 'Resmi tebligat gönderim ve teslim takip şablonu',
    icon: '⚖️',
    color: '#ef4444',
    category: 'hukuk',
    tags: ['tebligat', 'hukuk', 'posta', 'teslim'],
    defaultTip: 'giden',
    defaultDurum: 'beklemede',
    fields: [
      { key: 'tebligat_no', label: 'Tebligat No', type: 'text', required: true, width: 'sm' },
      { key: 'muhatap', label: 'Muhatap', type: 'text', required: true, width: 'lg' },
      { key: 'tc_no', label: 'TC / Vergi No', type: 'text', required: false, width: 'md' },
      { key: 'adres', label: 'Adres', type: 'textarea', required: true, width: 'full' },
      { key: 'tebligat_konusu', label: 'Tebligat Konusu', type: 'text', required: true, width: 'full' },
      { key: 'gonderim_tarihi', label: 'Gönderim Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'ptt_takip_no', label: 'PTT Takip No', type: 'text', required: false, width: 'md' },
      { key: 'teslim_tarihi', label: 'Teslim Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'tebligat_durumu', label: 'Tebligat Durumu', type: 'select', required: false, width: 'md', options: ['Gönderildi', 'Teslim Edildi', 'İade', 'Meçhul', 'Bırakıldı'] },
      { key: 'aciklama', label: 'Açıklama', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'fatura_takip',
    name: 'Fatura / Ödeme Takibi',
    description: 'Gelen ve giden fatura ile ödeme emirleri takip şablonu',
    icon: '🧾',
    color: '#8b5cf6',
    category: 'muhasebe',
    tags: ['fatura', 'ödeme', 'muhasebe', 'tahakkuk'],
    defaultTip: 'gelen',
    defaultDurum: 'beklemede',
    fields: [
      { key: 'fatura_no', label: 'Fatura No', type: 'text', required: true, width: 'sm' },
      { key: 'firma_adi', label: 'Firma Adı', type: 'text', required: true, width: 'lg' },
      { key: 'vergi_no', label: 'Vergi No', type: 'text', required: false, width: 'md' },
      { key: 'fatura_tarihi', label: 'Fatura Tarihi', type: 'date', required: true, width: 'sm' },
      { key: 'vade_tarihi', label: 'Vade Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'tutar', label: 'Tutar (₺)', type: 'text', required: true, width: 'sm' },
      { key: 'kdv_orani', label: 'KDV Oranı (%)', type: 'select', required: false, width: 'sm', options: ['0', '1', '10', '20'] },
      { key: 'odeme_sekli', label: 'Ödeme Şekli', type: 'select', required: false, width: 'sm', options: ['Nakit', 'Havale/EFT', 'Çek', 'Kredi Kartı'] },
      { key: 'odeme_durumu', label: 'Ödeme Durumu', type: 'select', required: false, width: 'md', options: ['Beklemede', 'Kısmi Ödendi', 'Ödendi', 'İptal', 'İtirazlı'] },
      { key: 'aciklama', label: 'Açıklama', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'kisi_ozluk',
    name: 'Personel Özlük Dosyası',
    description: 'Personel bilgileri ve özlük belgeleri takip şablonu',
    icon: '👤',
    color: '#06b6d4',
    category: 'genel',
    tags: ['personel', 'özlük', 'ik', 'sgk'],
    defaultTip: 'ic',
    defaultDurum: 'aktif',
    fields: [
      { key: 'sicil_no', label: 'Sicil No', type: 'text', required: true, width: 'sm' },
      { key: 'ad_soyad', label: 'Ad Soyad', type: 'text', required: true, width: 'lg' },
      { key: 'tc_no', label: 'TC Kimlik No', type: 'text', required: true, width: 'md' },
      { key: 'unvan', label: 'Unvan', type: 'text', required: false, width: 'md' },
      { key: 'birim', label: 'Birim', type: 'text', required: false, width: 'md' },
      { key: 'ise_giris_tarihi', label: 'İşe Giriş Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'dogum_tarihi', label: 'Doğum Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'egitim_durumu', label: 'Eğitim Durumu', type: 'select', required: false, width: 'md', options: ['İlkokul', 'Ortaokul', 'Lise', 'Ön Lisans', 'Lisans', 'Yüksek Lisans', 'Doktora'] },
      { key: 'sgk_sicil', label: 'SGK Sicil No', type: 'text', required: false, width: 'md' },
      { key: 'personel_durumu', label: 'Personel Durumu', type: 'select', required: false, width: 'md', options: ['Aktif', 'İzinde', 'Raporlu', 'Görevden Uzaklaştırıldı', 'Emekli', 'İstifa', 'Çıkarıldı'] },
      { key: 'aciklama', label: 'Notlar', type: 'textarea', required: false, width: 'full' },
    ],
  },
  {
    id: 'is_kazasi',
    name: 'İş Kazası / Ramak Kala',
    description: 'İş sağlığı ve güvenliği olay bildirim şablonu',
    icon: '🦺',
    color: '#f97316',
    category: 'is_sagligi',
    tags: ['isg', 'iş kazası', 'ramak kala', 'osg'],
    defaultTip: 'ic',
    defaultDurum: 'beklemede',
    fields: [
      { key: 'bildirim_no', label: 'Bildirim No', type: 'text', required: true, width: 'sm' },
      { key: 'olay_tarihi', label: 'Olay Tarihi', type: 'date', required: true, width: 'sm' },
      { key: 'olay_saati', label: 'Olay Saati', type: 'text', required: false, width: 'sm', hint: 'Örn: 14:30' },
      { key: 'kaza_turu', label: 'Kaza Türü', type: 'select', required: true, width: 'md', options: ['İş Kazası', 'Meslek Hastalığı', 'Ramak Kala', 'Tehlikeli Durum'] },
      { key: 'calisanin_adi', label: 'Çalışanın Adı', type: 'text', required: true, width: 'lg' },
      { key: 'birim', label: 'Birim / Departman', type: 'text', required: false, width: 'md' },
      { key: 'olay_yeri', label: 'Olay Yeri', type: 'text', required: true, width: 'md' },
      { key: 'olay_aciklamasi', label: 'Olay Açıklaması', type: 'textarea', required: true, width: 'full' },
      { key: 'alinan_onlem', label: 'Alınan Önlem', type: 'textarea', required: false, width: 'full' },
      { key: 'sgk_bildirimi', label: 'SGK Bildirimi', type: 'select', required: false, width: 'sm', options: ['Yapılmadı', 'Yapıldı', 'Gerekmiyor'] },
      { key: 'durum', label: 'Durum', type: 'select', required: false, width: 'md', options: ['Açık', 'İncelemede', 'Kapatıldı'] },
    ],
  },
  {
    id: 'ihale_takip',
    name: 'İhale Takip',
    description: 'Kamu ihale süreci ve sözleşme takip şablonu',
    icon: '📋',
    color: '#84cc16',
    category: 'genel',
    tags: ['ihale', 'satın alma', 'sözleşme', 'kamu'],
    defaultTip: 'ic',
    defaultDurum: 'hazırlık',
    fields: [
      { key: 'ihale_no', label: 'İhale No', type: 'text', required: true, width: 'sm' },
      { key: 'ihale_konusu', label: 'İhale Konusu', type: 'text', required: true, width: 'full' },
      { key: 'ihale_turu', label: 'İhale Türü', type: 'select', required: true, width: 'md', options: ['Açık İhale', 'Belli İstekliler Arasında', 'Pazarlık Usulü', 'Doğrudan Temin'] },
      { key: 'tahmini_bedel', label: 'Tahmini Bedel (₺)', type: 'text', required: false, width: 'md' },
      { key: 'ilan_tarihi', label: 'İlan Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'ihale_tarihi', label: 'İhale Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'kazanan_firma', label: 'Kazanan Firma', type: 'text', required: false, width: 'lg' },
      { key: 'sozlesme_bedeli', label: 'Sözleşme Bedeli (₺)', type: 'text', required: false, width: 'md' },
      { key: 'sozlesme_tarihi', label: 'Sözleşme Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'is_bitis_tarihi', label: 'İş Bitiş Tarihi', type: 'date', required: false, width: 'sm' },
      { key: 'ihale_durumu', label: 'İhale Durumu', type: 'select', required: false, width: 'md', options: ['Hazırlık', 'İlanda', 'İptal', 'Sonuçlandı', 'Sözleşme Aşaması', 'Devam Ediyor', 'Tamamlandı'] },
      { key: 'aciklama', label: 'Açıklama', type: 'textarea', required: false, width: 'full' },
    ],
  },
];
